[package]
name = 'campaign_manager'
version = '1.0.0'
authors = ['Hive Data Marketplace']

[addresses]
campaign_manager = "0xcafe"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "aptos-cli-v1.0.0" }
